---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: 如果您只是想快速找到问题的答案，此常见问题解答可以为您提供帮助。 
---
= 关于NetApp数据分类的常见问题解答
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您只是想快速找到问题的答案，此常见问题解答可以为您提供帮助。



== NetApp数据分类

以下问题提供了对数据分类的一般了解。



=== 数据分类如何工作？

数据分类在NetApp控制台系统和存储系统旁边部署了另一层 AI。然后，它会扫描卷、存储桶、数据库和其他存储帐户上的数据，并对找到的数据洞察进行索引。数据分类利用人工智能和自然语言处理，而不是通常围绕正则表达式和模式匹配构建的替代解决方案。

数据分类使用人工智能来提供数据的上下文理解，以便进行准确的检测和分类。它由人工智能驱动，因为它是针对现代数据类型和规模而设计的。它还了解数据背景，以便提供强大、准确的发现和分类。

link:concept-classification.html["详细了解数据分类的工作原理"] 。



=== 数据分类是否有 REST API，它是否可以与第三方工具一起使用？

是的，数据分类有一个 REST API，用于支持控制台核心平台一部分的数据分类版本中的功能。看link:api-classification.html["API 文档"] 。



=== 数据分类是否可以通过云市场获得？

数据分类是NetApp控制台核心功能的一部分，因此您不需要使用此服务的市场。



== 数据分类扫描和分析

以下问题与数据分类扫描性能和分析有关。



=== 数据分类多久扫描一次我的数据？

虽然初始数据扫描可能需要一点时间，但后续扫描仅检查增量变化，从而减少系统扫描时间。数据分类以循环方式连续扫描您的数据，每次扫描六个存储库，以便所有更改的数据都能快速分类。

link:task-scanning-overview.html["了解扫描的工作原理"] 。

数据分类每天仅扫描数据库一次；数据库不像其他数据源那样被连续扫描。

数据扫描对您的存储系统和数据的影响可以忽略不计。



=== 扫描性能是否有所不同？

扫描性能可能因网络带宽和环境中的平均文件大小而异。它还取决于主机系统（在云端或本地）的大小特征。请参阅link:concept-classification.html["数据分类实例"]和link:task-deploy-overview.html["部署数据分类"]了解更多信息。

在最初添加新的数据源时，您还可以选择仅执行“映射”（Mapping only）扫描，而不是完整的“分类”（Map & Classify）扫描。由于它不需要访问文件来查看其中的数据，因此可以非常快速地在数据源上完成映射。link:task-scanning-overview.html["查看映射和分类扫描之间的区别"] 。



=== 我可以使用数据分类搜索我的数据吗？

数据分类提供了广泛的搜索功能，可以轻松地在所有连接的源中搜索特定文件或数据。数据分类使用户能够进行比元数据所反映的更深入的搜索。它是一种与语言无关的服务，还可以读取文件并分析多种敏感数据类型，例如名称和 ID。例如，用户可以在结构化和非结构化数据存储中进行搜索，以查找可能从数据库泄露到用户文件的数据，从而违反公司政策。可以保存搜索结果以供日后使用，并且可以创建策略以设定的频率搜索并对结果采取行动。

一旦找到感兴趣的文件，就可以列出其特征，包括标签、系统帐户、存储桶、文件路径、类别（来自分类）、文件大小、上次修改、权限状态、重复、敏感度级别、个人数据、文件内的敏感数据类型、所有者、文件类型、文件大小、创建时间、文件哈希、数据是否分配给寻求其关注的人等等。可以使用过滤器来筛选出不相关的特征。

如果存在正确的权限，数据分类还具有基于角色的访问控制 (RBAC)，允许移动或删除文件。如果没有正确的权限，则可以将任务分配给组织中具有正确权限的人员。



== 数据分类管理和隐私

以下问题提供了有关如何管理数据分类和隐私设置的信息。



=== 如何启用或禁用数据分类？

首先，您需要在控制台或本地系统中部署数据分类实例。实例运行后，您可以从“配置”选项卡或通过选择特定系统在现有系统、数据库和其他数据源上启用该服务。link:task-getting-started-compliance.html["了解如何开始"] 。


NOTE: 在数据源上激活数据分类将立即导致初始扫描。扫描结果很快就会显示。

您可以从数据分类配置页面禁用数据分类扫描单个系统、数据库或文件共享组。看link:task-managing-compliance.html["从数据分类中删除数据源"] 。

要完全删除数据分类实例，请从云提供商的门户或本地位置手动删除数据分类实例。



=== 该服务可以排除某些目录中的扫描数据吗？

是如果您希望数据分类排除驻留在特定数据源目录中的扫描数据，则可以将该列表提供给分类引擎。应用该更改后，数据分类将排除指定目录中的扫描数据。link:task-exclude-scan-paths.html["了解更多"] 。



=== 是否扫描了位于ONTAP卷上的快照？

否。数据分类不会扫描快照，因为其内容与卷中的内容相同。



=== 如果在ONTAP卷上启用了数据分层，会发生什么情况？

当数据分类使用仅映射扫描扫描具有分层到对象存储的冷数据的卷时，它会扫描所有数据 - 本地磁盘上的数据和分层到对象存储的冷数据。对于实施分层的非NetApp产品来说也是如此。

仅映射扫描不会使冷数据升温——它会保持冷状态并保留在对象存储中。另一方面，如果您执行地图和分类扫描，某些配置可能会使冷数据升温。



== 源系统和数据类型的类型

以下问题涉及可以扫描的存储类型以及扫描的数据类型。



=== 在政府区域部署时有什么限制吗？

当控制台代理部署在政府区域（AWS GovCloud、Azure Gov 或 Azure DoD）时，支持数据分类 - 也称为“受限模式”。



=== 如果我在没有互联网访问的站点安装数据分类，我可以扫描哪些数据源？


IMPORTANT: BlueXP私有模式（传统BlueXP接口）通常用于没有互联网连接的本地环境和安全云区域，其中包括 AWS Secret Cloud、AWS Top Secret Cloud 和 Azure IL6。NetApp继续通过传统的BlueXP界面支持这些环境。有关旧版BlueXP界面中的私有模式文档，请参阅link:https://docs.netapp.com/us-en/console-setup-admin/media/BlueXP-Private-Mode-legacy-interface.pdf["BlueXP私人模式的 PDF 文档"^]。

数据分类只能扫描来自本地站点的数据源的数据。目前，数据分类可以以“私人模式”扫描以下本地数据源 - 也称为“暗”站点：

* 本地ONTAP系统
* 数据库模式
* 使用简单存储服务（S3）协议的对象存储




=== 支持哪些文件类型？

数据分类扫描所有文件的类别和元数据洞察，并在仪表板的文件类型部分显示所有文件类型。

当数据分类检测到个人身份信息 (PII) 或执行 DSAR 搜索时，仅支持以下文件格式：

`+.CSV, .DCM, .DOC, .DOCX, .JSON, .PDF, .PPTX, .RTF, .TXT, .XLS, .XLSX, Docs, Sheets, and Slides+`



=== 数据分类捕获哪些类型的数据和元数据？

数据分类使您能够对数据源运行常规“映射”扫描或完整“分类”扫描。映射仅提供数据的高级概述，而分类提供数据的深层扫描。由于它不需要访问文件来查看其中的数据，因此可以非常快速地在数据源上完成映射。

* *数据映射扫描（仅映射扫描）*：数据分类仅扫描元数据。这对于整体数据管理和治理、快速项目范围界定、大型地产和优先级排序很有用。数据映射基于元数据，被认为是一种*快速*扫描。
+
快速扫描后，您可以生成数据映射报告。此报告概述了您公司数据源中存储的数据，以帮助您做出有关资源利用率、迁移、备份、安全性和合规性流程的决策。

* *数据分类深度扫描（地图和分类扫描）*：数据分类使用标准协议和只读权限在您的整个环境中扫描数据。打开选定的文件并扫描其中的敏感业务相关数据、私人信息以及与勒索软件相关的问题。
+
完整扫描后，您可以将许多附加数据分类功能应用于数据，例如在数据调查页面中查看和优化数据、在文件中搜索名称、复制、移动和删除源文件等。



数据分类捕获元数据，例如：文件名、权限、创建时间、上次访问和上次修改。这包括数据调查详情页面和数据调查报告中显示的所有元数据。

数据分类可以识别多种类型的私人数据，例如个人信息（PII）和敏感个人信息（SPII）。有关私人数据的详细信息，请参阅xref:reference-private-data-categories.html[数据分类扫描的私人数据类别]。



=== 我可以将数据分类信息限制给特定用户吗？

是的，数据分类与NetApp控制台完全集成。  NetApp控制台用户只能查看根据其权限有资格查看的系统的信息。

此外，如果您希望允许某些用户仅查看数据分类扫描结果而无权管理数据分类设置，则可以为这些用户分配*分类查看器*角色（在标准模式下使用NetApp控制台时）或*合规性查看器*角色（在受限模式下使用NetApp控制台时）。link:concept-classification.html["了解更多"] 。



=== 任何人都可以访问我的浏览器和数据分类之间发送的私人数据吗？

不可以。您的浏览器和数据分类实例之间发送的私人数据使用 TLS 1.2 进行端到端加密保护，这意味着NetApp和非NetApp方都无法读取它。除非您请求并批准访问，否则数据分类不会与NetApp共享任何数据或结果。

扫描的数据保留在您的环境中。



=== 敏感数据如何处理？

NetApp无法访问敏感数据，也不会在 UI 中显示它。敏感数据被屏蔽，例如，显示信用卡信息的最后四位数字。



=== 数据存储在哪里？

扫描结果存储在数据分类实例内的 Elasticsearch 中。



=== 如何访问数据？

数据分类通过 API 调用访问存储在 Elasticsearch 中的数据，这些调用需要身份验证并使用 AES-128 加密。直接访问 Elasticsearch 需要 root 访问权限。



== 许可证和费用

以下问题涉及使用数据分类的许可和成本。



=== 数据分类的费用是多少？

数据分类是NetApp控制台的核心功能。沒有扣費。



== 控制台代理部署

以下问题与控制台代理有关。



=== 什么是控制台代理？

控制台代理是在您的云帐户或本地的计算实例上运行的软件，它使NetApp控制台能够安全地管理云资源。您必须部署控制台代理才能使用数据分类。



=== 控制台代理需要安装在哪里？

扫描数据时，需要在以下位置安装NetApp Console 代理：

* 对于 AWS 中的Cloud Volumes ONTAP或Amazon FSx for ONTAP：控制台代理位于 AWS 中。
* 对于 Azure 或Azure NetApp Files中的Cloud Volumes ONTAP ：控制台代理位于 Azure 中。
* 对于 GCP 中的Cloud Volumes ONTAP ：控制台代理位于 GCP 中。
* 对于本地ONTAP系统：控制台代理位于本地。


如果您在这些位置有数据，您可能需要使用 https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["多个控制台代理"^]。



=== 数据分类是否需要访问凭证？

数据分类本身不会检索存储凭证。相反，它们存储在控制台代理中。

数据分类使用数据平面凭证（例如 CIFS 凭证）在扫描之前挂载共享。



=== 服务和控制台代理之间的通信是否使用 HTTP？

是的，数据分类使用 HTTP 与控制台代理进行通信。



== 数据分类部署

以下问题与单独的数据分类实例有关。



=== 数据分类支持哪些部署模型？

NetApp控制台允许用户在几乎任何地方扫描和报告系统，包括本地、云和混合环境。数据分类通常使用 SaaS 模型部署，其中服务通过控制台界面启用，不需要安装硬件或软件。即使在这种点击即运行的部署模式下，无论数据存储是在本地还是在公共云中，都可以进行数据管理。



=== 数据分类需要什么类型的实例或虚拟机？

什么时候link:task-deploy-cloud-compliance.html["部署在云端"]：

* 在 AWS 中，数据分类在具有 500 GiB GP2 磁盘的 m6i.4xlarge 实例上运行。您可以在部署期间选择较小的实例类型。
* 在 Azure 中，数据分类在具有 500 GiB 磁盘的 Standard_D16s_v3 VM 上运行。
* 在 GCP 中，数据分类在具有 500 GiB 标准持久磁盘的 n2-standard-16 VM 上运行。


link:concept-classification.html["详细了解数据分类的工作原理"] 。



=== 我可以在自己的主机上部署数据分类吗？

是您可以在网络或云中具有互联网访问权限的 Linux 主机上安装数据分类软件。一切运作相同，您可以继续通过控制台管理扫描配置和结果。看link:task-deploy-compliance-onprem.html["在本地部署数据分类"]了解系统要求和安装详情。



=== 没有互联网接入的安全站点怎么样？

是的，也支持。你可以link:task-deploy-compliance-dark-site.html["在没有互联网访问权限的本地站点中部署数据分类"]以获得完全安全的网站。
