---
sidebar: sidebar 
permalink: task-deploy-overview.html 
keywords: cloud compliance, data sense, get started, deploy cloud data sense, outbound internet, endpoints, cloud compliance internet, web browser connectivity, cloud compliance access, privacy, compliance, bluexp classification 
summary: 规划哪种NetApp Data Classification部署可以满足您的需求。 
---
= 选择您的 NetApp Data Classification 部署方法
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以通过不同的方式部署 NetApp Data Classification。查看可用的方法，选择最适合您需求的方法。

* link:task-deploy-cloud-compliance.html["使用控制台在云中部署"] 。控制台将数据分类实例部署在与控制台代理相同的云提供商网络中。
* link:task-deploy-compliance-onprem.html["在可以访问互联网的 Linux 主机上安装"] 。在您的网络中的 Linux 主机上或云中的 Linux 主机上安装数据分类，前提是该主机可以访问互联网。如果您希望使用同样位于本地的数据分类实例来扫描本地ONTAP系统，则这种类型的安装可能是一个不错的选择，尽管这不是必需的。
* link:task-deploy-compliance-dark-site.html["在没有互联网访问的本地站点的 Linux 主机上安装"]，也称为_私人模式_。这种安装类型使用安装脚本，与控制台 SaaS 层没有连接。



TIP: 对于本地 VMware vSphere 部署，Data Classification 支持简化的link:task-deploy-ova.html["使用 OVA 部署"]。



== 本地安装脚本

具有 Internet 访问权限的 Linux 主机上的安装和没有 Internet 访问权限的 Linux 主机上的本地安装都使用安装脚本。脚本首先检查系统和环境是否满足先决条件。如果满足先决条件，则开始安装。

有一个单独的软件包可用于验证您的 Linux 的准备情况。要运行验证包，请参见link:task-test-linux-system.html["验证您的 Linux 主机是否已准备好安装 Data Classification"]。
