= 1.40 版
:allow-uri-read: 




=== 1.40 版

此BlueXP classification版本包括以下更新。

.支持 RHEL 9.5
此版本除了支持以前支持的版本外，还提供对 Red Hat Enterprise Linux v9.5 的支持。这适用于BlueXP classification的任何手动本地安装，包括暗站部署。

以下操作系统需要使用 Podman 容器引擎，并且需要BlueXP classification版本 1.30 或更高版本：Red Hat Enterprise Linux 版本 8.8、8.10、9.0、9.1、9.2、9.3、9.4 和 9.5。

.优先进行仅映射扫描
当进行仅映射扫描时，您可以优先考虑最重要的扫描。当您拥有多个工作环境并希望确保首先完成高优先级扫描时，此功能会有所帮助。

默认情况下，扫描按照启动的顺序排队。通过设置扫描优先级，您可以将扫描移至队列的最前面。可以对多个扫描进行优先排序。优先级按先进先出的顺序指定，这意味着您优先考虑的第一个扫描将移至队列的最前面；您优先考虑的第二个扫描将成为队列中的第二个扫描，依此类推。

优先权是一次性授予的。映射数据的自动重新扫描按照默认顺序进行。

优先级仅限于link:https://docs.netapp.com/us-en/bluexp-classification/concept-classification.html["仅映射扫描"^]；它不适用于地图和分类扫描。

有关更多信息，请参阅link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["优先扫描"^] 。

.重试所有扫描
BlueXP classification支持批量重试所有失败扫描的功能。

您可以使用**全部重试**功能以批量操作的方式重新尝试扫描。如果分类扫描由于网络中断等临时问题而失败，您可以使用一个按钮同时重试所有扫描，而不必单独重试。可以根据需要重试扫描多次。

要重试所有扫描：

. 从BlueXP classification菜单中，选择 *配置*。
. 要重试所有失败的扫描，请选择*重试所有扫描*。


.提高分类模型的准确性
机器学习模型的准确率link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["预定义类别"]提高了11%。
